# Generated by Django 4.2.5 on 2023-09-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C_Dashboard', '0002_usuario_cuestionarioinicial_cuestionariofinal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='usuarioID',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='cuestionariofinal',
            name='usuarioID',
        ),
        migrations.RemoveField(
            model_name='cuestionarioinicial',
            name='usuarioID',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='CuestionarioFinal',
        ),
        migrations.DeleteModel(
            name='CuestionarioInicial',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
