# Generated by Django 4.2.5 on 2023-09-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('avance', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('edad', models.IntegerField(max_length=5)),
                ('pais', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('diciplina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuestionarioInicial',
            fields=[
                ('preguntaID', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=50)),
                ('usuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CuestionarioFinal',
            fields=[
                ('preguntaID', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=50)),
                ('usuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('actividadID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=15)),
                ('entregable', models.CharField(max_length=7000)),
                ('usuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
