# Generated by Django 4.2.5 on 2023-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_actividad_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(choices=[(1, '1.- Identificación'), (2, '2.- Investigación'), (3, '3.- Ideación'), (4, '4.- Socialización'), (5, 'Entregable final')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
