# Generated by Django 4.2.5 on 2023-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_actividad_entregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='entregable',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
