# Generated by Django 4.2.5 on 2023-10-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_actividad_entregable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionariofinal',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='cuestionarioinicial',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='cuestionariofinal',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuestionarioinicial',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
