# Generated by Django 4.2.5 on 2023-10-08 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_actividad_estatus_alter_actividad_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioNombre',
            fields=[
                ('solicitudNID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estatus', models.CharField(max_length=50)),
                ('usuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CambioContrasenia',
            fields=[
                ('solicitudCID', models.AutoField(primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=50)),
                ('estatus', models.CharField(max_length=50)),
                ('usuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
