# Generated by Django 4.2.5 on 2023-10-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_usuario_avance_alter_usuario_contrasenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avance',
            field=models.IntegerField(default=0),
        ),
    ]
