# Generated by Django 4.2.5 on 2023-10-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='diciplina',
            field=models.CharField(blank=True, choices=[('Ingenieria y ciencias', 'Ingenieria y ciencias'), ('Humanidades y ciencia', 'Humanidades y ciencia'), ('Ciencias sociales', 'Ciencias sociales'), ('Ciencias de la salud', 'Ciencias de la salud'), ('Arquitectura, Arte y Diseño', 'Arquitectura, Arte y Diseño'), ('Negocios', 'Negocios')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(blank=True, choices=[('Pregrado (licenciatura, profesional, universidad, grado)', 'Pregrado (licenciatura, profesional, universidad, grado)'), ('Posgrado (maestría, doctorado)', 'Posgrado (maestría, doctorado)'), ('Educación continua', 'Educación continua')], max_length=100),
        ),
    ]
